### ISSUE TITLE
[feat] use same buffer for multiple code chunks (+ collaboration ideas)

### ISSUE THREAD

**Issue by jmbuhr** [AckslD/nvim-FeMaco.lua#20]
Hi there, really cool plugin! I love your idea of using floating windows.

I have been trying to implement code completion, dignostics and the likes for https://github.com/quarto-dev/quarto-nvim, the neovim plugin for [quarto](https://quarto.org/) (plain text computational notebooks for R / python /  julia / java script which you can render to any output format, such as presentations, websites, pdfs etc.).

Would you be open to contributions to increase interoperability between the plugins? For example, one feature I would love to port to your plugin is the ability to use the same buffer / temporary file for all code chunks of the same language within one document.

This would mean, that e.g.

````
```{python}
def hello():
  print('hello')
```

```{python}
hello()
```
````
wouldn't suffer from
![image](https://user-images.githubusercontent.com/17450586/195854882-104f33a9-2651-4d20-b195-7853222c69ff.png)

I have a function to create a hidden buffer (coupled to a file) with the language content of a file (via treesitter), that can be synchronized to the source document and shares line numbers because the non-language lines are simply set to empty lines: https://github.com/quarto-dev/quarto-nvim/blob/ab3995baa8e975718ba7023451b7a2a308a876e2/lua/quarto/init.lua#L134-L163

My struggle was with showing things from this hidden buffer in the main source document, but I think your idea solves this very elegantly!

**Comment by AckslD** [comment]
Hi @jmbuhr! Thanks, I'm happy you like it! :)

I think this sounds really cool and I'm very happy with some collaboration. Would you like to open a PR for this feature?

Some questions I have:
* Should this be an optional feature? Ie you can either open a single code-block or a merged version, either with separate commands or through settings.
* How would you handle injections of different languages in a single file? Ie if I have a markdown file with injected `python` and `rust`. I guess only the `python` injections should be included if you open a `python`-injection?
* How should `inline` injections be handled?

Btw, I'd like to also look into quarto, looks nice but I never used it.

**Comment by jmbuhr** [comment]
Yes, I would love to try my hand at this.

- Re: optional: Good question. Maybe this should be separate commands. But I also wonder if it wouldn't be desirable to always have the whole context. Though this is just what I am used to after having used Rmarkdown (the predecessor to quarto which was focussed on the R language) for so long. The only usecase I could think of is when you want to explain language features in an imutable language and you want to re-use variable names in the code chunks without e.g. the haskell language server complaining that `x` is already defined. But here we have precedence because Haskell already has a literate programming format (literate haskell), which compiles down to haskell and does not treat code chunks independently.
- Re: different languages: I create one file + hidden buffer per language. These are the files created from the original qmd on the left:

![image](https://user-images.githubusercontent.com/17450586/196377097-8ec50c61-6d37-4e5a-bc01-2c83ce5e05e7.png)

- As of now I am not detecting inlines (treesitter does not have the language string for those, so we need to parse the string manually), but they should probably be added. In most cases it should be straightforward, since there should be space in the respective language buffer, but it might break if two separate inlines of the same language are in the same line. In this case we would need to add a separator between the two, which would be language specific (and this already sounds like a pain)... so  whole code chunks are the lower hanging fruit.

**Comment by AckslD** [comment]
Btw, one thing to point out (although maybe it was already clear :)) which is relevant to all the above points is that `femaco` supports any language injections in any language, not only in markdown for example. So this might be SQL injections in go or anything else. So I think for this reason a separate command might be good since in these cases you might not want to merge all SQL injections.

> I create one file + hidden buffer per language. 

Nice!

> As of now I am not detecting inlines (treesitter does not have the language string for those, so we need to parse the string manually), but they should probably be added.

If useful you can see how this is done in `femaco` [here](https://github.com/AckslD/nvim-FeMaco.lua/blob/main/lua/femaco/edit.lua#L46). We get the language directly from treesitter, rather than parsing the string.

> but it might break if two separate inlines of the same language are in the same line.

Yes, this was cases I wasn't sure about, but we can see if just using the whitespace the buffer gets by default works. Especially if we have separate commands for the merged vs non-merged versions.

**Comment by jmbuhr** [comment]
That makes sense, I hadn't thought about SQL as something where individual code chunks are not connected.

So it definitely will be a separate command. This command could differ in another way: Because when we are dealing with connected code chunks they might also be connected to other files in the same project (e.g. importing a local python module or sourcing an R script to expose function). The language server can take into account when we use a file in the same folder to hold the extracted source code, as opposed to individual chunks, which work with temporary files in the `tmp` folder just fine.

**Comment by jmbuhr** [comment]
Hey there and sorry for the radio silence. I ended up going a different route to address the problem, hence no PR to FeMaco ever manifested. However, you might actually like this approach as well: https://github.com/jmbuhr/otter.nvim

It has otters! Because as it turns out we both like metaphor driven architecture, a term I think we should coin.

**Comment by AckslD** [comment]
That looks awesome🎉, looking forward to try it out and add an otter plugin to my config ;)
