### ISSUE TITLE
Handle language specific settings

### ISSUE THREAD

**Issue by Piotr1215** [AckslD/nvim-FeMaco.lua#22]
I'm trying to create a language specific settings for `FeMaco` and `rust`. So far I got this working, but it seems pretty _hacky_. Is there a better, idiomatic way to configure language specific behavior in `FeMaco`?

I have also thought about creating a `user command`, but this was easier.

```lua
require('femaco').setup({
  -- return filetype to use for a given lang
  -- lang can be nil
  ft_from_lang = function(lang)
    Language = lang
    return lang
  end,
  -- what to do after opening the float
  post_open_float = function(winnr)
    if Language == "rust" then
      require('rust-tools.standalone').start_standalone_client()
    end
  end
})
```

**Comment by AckslD** [comment]
Could you maybe instead access `vim.bo.filetype` in `post_open_float`?

**Comment by Piotr1215** [comment]
Thank you, that worked and is much faster than my original idea.
