### ISSUE TITLE
Extend functionality to any buffer with injected language blocks?

### ISSUE THREAD

**Issue by bew** [AckslD/nvim-FeMaco.lua#3]
Hello!

This plugin looks nice & simple :+1: 

Have you considered making it work in all files (not just markdown), to support any language block injected in a base language using treesitter ?

**Comment by AckslD** [comment]
Hi @bew! I think this would be great indeed. What I don't know is how uniform the structure for injected languages are. For example at the moment we make use of eg the following structure:
```
fenced_code_block [2, 0] - [5, 0]
  fenced_code_block_delimiter [2, 0] - [2, 3]
  info_string [2, 3] - [2, 9]
    language [2, 3] - [2, 9]
  block_continuation [3, 0] - [3, 0]
  code_fence_content [3, 0] - [4, 0]
    ...
  fenced_code_block_delimiter [4, 0] - [4, 3]
```
to both find what the injected language is and where the content lives in the buffer. Maybe there are other ways to retrieve this without querying the tree directly. If so, I'd be interested in knowing this :)

**Comment by bew** [comment]
With a quick look at the documentation around treesitter, I've found the functions around LanguageTrees:
https://neovim.io/doc/user/treesitter.html#treesitter-languagetree

I didn't test anything, but it looks like you might not even need to navigate the parsed tree yourself, matching individual nodes, but instead you should be able to access directly the current injected language, where it starts/ends, etc...

Edit: Looking a bit more at neovim's & nvim-treesitter's source code, the parser you get from `parsers.get_parser(0)` is actually a `LanguageTree` object \o/

**Comment by AckslD** [comment]
This looks great and might indeed be a better way and more powerful. Thanks for sharing! I'll try to take a look at this 👍

**Comment by AckslD** [comment]
@bew I started trying this out in #4, feel free to try it if it works for you. It does seem to work pretty well I think.

One small issue is that if you for example have an empty codeblock in markdown, eg:
```
\```python
\```
```
then there is in fact no injected language tree there and you can't selected. Also for a similar reason you currently only be able to open the window when you're on the start (back-ticks) of the code-block but not the last line with back-ticks.

**Comment by bew** [comment]
Hmm that's too bad..
Does it work if you add an empty line in code block and trigger the plugin there? 

As far for trying, you'll have to wait a bit, as I'm in the process of migrating my conf to Lua, with all the new things like treesitter.
I don't have treesitter setup yet, but I should be able to try in a few days (:

**Comment by ziontee113** [comment]
HI @AckslD , what do you think about the option of letting the user to use their own Treesittter queries?

**Comment by AckslD** [comment]
That might be the way to go indeed @ziontee113, ideally this would work automatically for any language injection but doesn't seem feasible since "empty" languages are not injected (which I guess makes sense).

Do you have some language with a query in mind that I could try out as an example?

**Comment by ziontee113** [comment]
You can take a look at this screenshot

![Screenshot from 2022-09-10 19-37-54](https://user-images.githubusercontent.com/102876811/189483713-66245f50-dc20-4e13-8a84-10b0e273051d.png)

We're in a `lua` file, and I can inject `query` (or `scheme`) into that string `query_template [[ ]]`. All I need is in my nvim config: `after/queries/lua/injections.lua`:

```scheme
(
 ("string_content") @query
 (#match? @query ";; query")
)
```

Only strings that has the `;; query` in it will be highlighted.

**Comment by AckslD** [comment]
Thanks!

Actually, this got me thinking, maybe we can also just extend eg the current markdown query to also match empty code-blocks. So I tried changing current injections.scm for markdown to something like:
```
;; matches non-empty code-blocks
(fenced_code_block
  (info_string
    (language) @language)
  (#not-match? @language "elm")
  (code_fence_content) @content (#exclude_children! @content))

;; matches empty code-blocks
(fenced_code_block
  (info_string
    (language) @language)
  (#not-match? @language "elm")
  (block_continuation) @content
  .
  (fenced_code_block_delimiter))
```
This seems to indeed work. So I updated #4 to instead find matches of language injections queries. Feel free to try it if it works for you.

~I also tried to add the second query in `after/queries/markdown/injections.scm` but that did not work for some reason, not sure why yet.~

Note that `femaco` currently assumes that whatever surrounds the content of the injection is on separate lines. One could maybe change that but not sure it's useful and would then anyway be a separate feature.

Edit: turns out I just forgot `;; extends` in the `after` query. So #4 should now work out of the box without editing any queries.

**Comment by AckslD** [comment]
One more thing I just realised is that is currently only works for injections with matches `@language` and `@content`. If I'm not mistaken, injection queries can also be a single match where the name of the match is the language. This is easy to fix though

Edit: fixed by #6

**Comment by AckslD** [comment]
#8 now enables also inline injections

for example see the following example where lua is temporarily injected into python strings:


https://user-images.githubusercontent.com/23341710/189546136-fc555484-76f9-46c2-bdab-937f65044c47.mp4

**Comment by ziontee113** [comment]
This is awesome.

**Comment by AckslD** [comment]
Will just need to wait for https://github.com/nvim-treesitter/nvim-treesitter/pull/3486 :)
