### ISSUE TITLE
Question: future of nvim-FeMaco.lua

### ISSUE THREAD

**Issue by barrettruth** [AckslD/nvim-FeMaco.lua#30]
Hello AcksID, thanks for writing such a cool plugin. I think it paves the way for a feature I see (in due time) being in the neovim ecosystem: fully supported injection LSP seamlessly integrated with code editing.

I have two questions for now:

1. How can I configure nvim-FeMaco to work with javascript inside of a <script> tag in HTML? Understanding this example I think will help me figure out how any injected language can work.
2. How far off is seamless LSP integration with injected langauges (i.e., not needing a floating window? - like [otter.nvim](https://github.com/jmbuhr/otter.nvim), except, well, it actually works)

Thanks for your work!

**Comment by AckslD** [comment]
Thanks for your message @barrett-ruth! :)

1. You can inject any language in any other using queries. For example as a dummy example you can inject `lua` in `python` strings by:
   ```
   :lua vim.treesitter.set_query('python', 'injections', '((string) @lua (#offset! @lua 0 1 0 -1))')
   ```
   Or place it in the `queries/python/injections.scm`.
2. Not sure actually, at least I wouldn't know how to do it atm.

**Comment by barrettruth** [comment]
Awesome. Thanks for response. Need to brush up on my queries so I'll use this plugin as a chance to do that.
