### ISSUE TITLE
Question: When I use FeMaco to input a code, it will automatically insert `v:null`

### ISSUE THREAD

**Issue by tan-wei** [AckslD/nvim-FeMaco.lua#36]
For example, for this code block in Markdown below:
![图片](https://github.com/AckslD/nvim-FeMaco.lua/assets/28227509/51b1dce0-dca2-4801-a4de-2ad90edcacb5)

After I use `:FeMaco`, it will open a float window, but with existed code;
![图片](https://github.com/AckslD/nvim-FeMaco.lua/assets/28227509/7aa10a71-c9c8-495d-a817-1480818784ae)

How can I get rid of this `v:null` code? Thanks!

**Comment by AckslD** [comment]
Hmm, not sure I can reproduce, what versions of `nvim` and treesitter are you on?


https://github.com/AckslD/nvim-FeMaco.lua/assets/23341710/8d069b9f-d3d3-4b5a-a972-d6d5d557d726

**Comment by gegoune** [comment]
Someone reported something like that on formatter.nvim recently.

**Comment by AckslD** [comment]
Thanks for sharing @gegoune
https://github.com/mhartington/formatter.nvim/issues/241

Does the issue go away if you disable formatter.nvim @tan-wei ?

**Comment by tan-wei** [comment]
Yes, the issue disappeared after I disable formatter.nvim with C/C++, so it is related to the plugin not FeMaco.

**Comment by tan-wei** [comment]
Thanks @gegoune .
