### ISSUE TITLE
Split or separate buffer instead of floating window

### ISSUE THREAD

**Issue by vishalbalaji** [AckslD/nvim-FeMaco.lua#5]
Hello, this plugin is great! However, I was wondering if there was an option to open the code in a separate buffer or split instead of a floating window, or if there were any plans to implement this feature.

**Comment by AckslD** [comment]
This is currently not implemented, but I'm happy to get a PR for this :) We could for example just make the [`open_float`](https://github.com/AckslD/nvim-FeMaco.lua/blob/e94e857d7137d4e792995cb1a08e5c6ae1ae980e/lua/femaco/edit.lua#L64) function configurable. Currently it just does this:
```lua
local open_float = function(opts)
  local buf = vim.api.nvim_create_buf(false, false)
  return vim.api.nvim_open_win(buf, true, opts)
end
```
and if we expose this function in the settings you could open the window/buffer/split in any way you want.

**Comment by AndOrangutan** [comment]
> This is currently not implemented, but I'm happy to get a PR for this :) We could for example just make the [`open_float`](https://github.com/AckslD/nvim-FeMaco.lua/blob/e94e857d7137d4e792995cb1a08e5c6ae1ae980e/lua/femaco/edit.lua#L64) function configurable. Currently it just does this:
> 
> ```lua
> local open_float = function(opts)
>   local buf = vim.api.nvim_create_buf(false, false)
>   return vim.api.nvim_open_win(buf, true, opts)
> end
> ```
> 
> and if we expose this function in the settings you could open the window/buffer/split in any way you want.

That is exactly what I was looking for.

**Comment by AckslD** [comment]
You can now provide your own `prepare_buffer` setting to open the buffer in the way you prefer :)
